name: hiring_task
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

flutter_intl:
  enabled: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  logger: ^1.1.0
  auto_route: ^5.0.1
  dio: ^4.0.6
  yaml: ^3.1.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  injectable: ^1.5.3
  get_it: ^7.2.0
  dartz: ^0.10.1
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.1
  build_runner: ^2.2.0
  injectable_generator: ^1.5.4
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/config/